// <auto-generated />
using System;
using FermaOnline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FermaOnline.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FermaOnline.Models.Cage", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AverageBodyWeight")
                        .HasColumnType("real");

                    b.Property<float>("AverageWeightGain")
                        .HasColumnType("real");

                    b.Property<float>("AverageWeightGainFromStart")
                        .HasColumnType("real");

                    b.Property<int>("CageQuantity")
                        .HasColumnType("int");

                    b.Property<int>("DeathCount")
                        .HasColumnType("int");

                    b.Property<float>("DifferenceInBodyWeight")
                        .HasColumnType("real");

                    b.Property<float>("GroupWeight")
                        .HasColumnType("real");

                    b.Property<float>("IndividualBodyWeight")
                        .HasColumnType("real");

                    b.Property<float>("WeightGainFromLastSurvey")
                        .HasColumnType("real");

                    b.Property<float>("WeightGainFromStart")
                        .HasColumnType("real");

                    b.HasKey("SurveyId");

                    b.ToTable("Cage");
                });

            modelBuilder.Entity("FermaOnline.Models.Survey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ASurveyId")
                        .HasColumnType("int");

                    b.Property<int?>("BSurveyId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfLife")
                        .HasColumnType("int");

                    b.Property<int>("DaysFromFirstWeight")
                        .HasColumnType("int");

                    b.Property<float>("FeedConversionRatio")
                        .HasColumnType("real");

                    b.Property<float>("FeedIntakDaily")
                        .HasColumnType("real");

                    b.Property<float>("FeedIntakeWeekly")
                        .HasColumnType("real");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<float>("LoculusFeedIntake")
                        .HasColumnType("real");

                    b.Property<int>("LoculusQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SurveyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("SurveyId");

                    b.HasIndex("ASurveyId");

                    b.HasIndex("BSurveyId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("FermaOnline.Models.TemplateCurve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SurveyId")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("TemplateCurve");
                });

            modelBuilder.Entity("FermaOnline.Models.Survey", b =>
                {
                    b.HasOne("FermaOnline.Models.Cage", "A")
                        .WithMany()
                        .HasForeignKey("ASurveyId");

                    b.HasOne("FermaOnline.Models.Cage", "B")
                        .WithMany()
                        .HasForeignKey("BSurveyId");

                    b.Navigation("A");

                    b.Navigation("B");
                });

            modelBuilder.Entity("FermaOnline.Models.TemplateCurve", b =>
                {
                    b.HasOne("FermaOnline.Models.Survey", null)
                        .WithMany("TemplateCurve")
                        .HasForeignKey("SurveyId");
                });

            modelBuilder.Entity("FermaOnline.Models.Survey", b =>
                {
                    b.Navigation("TemplateCurve");
                });
#pragma warning restore 612, 618
        }
    }
}
